server_names = ['bn-fr0-ipv6','opennic-tumabox-ipv6','securedns-ipv6']
listen_addresses = ['[::]:53']
max_clients = 250
ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = false
doh_servers = false
require_dnssec = false
require_nolog = false
require_nofilter = false
force_tcp = false
timeout = 1000
cert_refresh_delay = 240
fallback_resolver = '8.8.8.8:53'
ignore_system_dns = true
log_level = 0
log_file = '/root/dnscrypt-proxy.log'
log_files_max_size = 1
log_files_max_age = 1
log_files_max_backups = 1
block_ipv6 = false
cache = true
cache_size = 256
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60
[query_log]
  format = 'tsv'
[nx_log]
  format = 'tsv'
[blacklist]
[ip_blacklist]
[schedules]
[sources]  
 # [sources.'public-resolvers']
 # url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
 # cache_file = 'public-resolvers.md'
 # minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
 # refresh_delay = 72
 # prefix = ''
[static]
  [static.'bn-fr0-ipv6']
  stamp = 'sdns://AQYAAAAAAAAAHFsyMDAxOjQxZDA6ODo0NDgwOjoyMjJdOjUzNTMgh5QHChQ9NcocpjLnsYkwKE6uXa_rtAHj31Lp8Der0YIfMi5kbnNjcnlwdC1jZXJ0LmJhYnlsb24ubmV0d29yaw'
  [static.'opennic-tumabox-ipv6']
  stamp = 'sdns://AQYAAAAAAAAAG1syYTAyOmUwMDpmZmZkOjEzOTo6OV06NTM1MyDVkXsRajUxFMI4qpmm6wwofPdoBUGsXb-ooCOeIoxbBg0yLnR1bWFib3gub3Jn'
  [static.'securedns-ipv6']
  stamp = 'sdns://AQcAAAAAAAAAIVsyYTAzOmIwYzA6MDoxMDEwOjplOWE6MzAwMV06NTM1MyCzpZdpFFdbBInhn66cQ-Z5-vKMVxiXADF_e7SWKR-wlRwyLmRuc2NyeXB0LWNlcnQuc2VjdXJlZG5zLmV1'

