#!/bin/sh
iptables -D INPUT -i tun0 -j ACCEPT
iptables -D FORWARD -i tun0 -j ACCEPT
iptables -t nat -D POSTROUTING -s 192.168.50.0/24 -o tun0 -j MASQUERADE
iptables -D INPUT -i tun0 -j ACCEPT
iptables -D FORWARD -i tun0 -j ACCEPT
iptables -t nat -D POSTROUTING -s 192.168.50.0/24 -o tun0 -j MASQUERADE
echo $1 
killall openvpn
while true
        do
           	sleep 1 
		        statuss=`ifconfig| grep tun0`
            if [[ -z "${statuss}" ]]; then
                  echo "link destroyed"
                  break
            fi
        done
rmmod tun
rm -rf /jffs/ovpn/openvpn.log
